/* Generated by Ward Newsletter Generator. */
import './App.css'

const newsletters = [{"periodKey":"2026-09","monthLabel":"September 2026","title":"Willow Wood Ward - September 2026","url":"https://willowwoodward.github.io/WardNewsletters/n/sfVmImYb6j_f9zRGHWOy0Imo/"},{"periodKey":"2026-10","monthLabel":"October 2026","isComingSoon":true}]

function App() {
  const showArchiveList = new URLSearchParams(window.location.search).get('view') === 'list'
  const publishedNewsletters = newsletters.filter((newsletter) => !newsletter.isComingSoon)
  const publishedByPeriod = new Map(publishedNewsletters.map((newsletter) => [newsletter.periodKey, newsletter]))
  const currentDate = new Date()
  const homeNewsletters = [0, 1].map((monthOffset) => {
    const periodDate = new Date(currentDate.getFullYear(), currentDate.getMonth() + monthOffset, 1)
    const periodKey = periodDate.getFullYear() + '-' + String(periodDate.getMonth() + 1).padStart(2, '0')
    return publishedByPeriod.get(periodKey) ?? {
      periodKey,
      monthLabel: periodDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' }),
      isComingSoon: true,
    }
  })
  const visibleNewsletters = showArchiveList ? publishedNewsletters : homeNewsletters

  return (
    <div className="archive-shell">
      <header className="archive-header">
        <div className="archive-brand">Willow Wood Ward</div>
        <a className="archive-qr-link" href={showArchiveList ? '/WardNewsletters/' : '?view=list'}>
          {showArchiveList ? 'Current months' : 'View All Newsletters'}
        </a>
      </header>
      <main className="archive-main">
        {!showArchiveList ? <h1 className="archive-title">Archived Newsletters</h1> : null}
        {!showArchiveList ? <p className="archive-intro">New monthly newsletters will appear here as they are published.</p> : null}
        {visibleNewsletters.length > 0 ? (
          <div className={'archive-list' + (showArchiveList ? ' archive-list-all' : '')} aria-label="Monthly newsletters">
            {visibleNewsletters.map((newsletter) => (
              <div key={newsletter.periodKey}>
                {newsletter.isComingSoon ? (
                  <div className="archive-card">
                    <div>
                      <div className="archive-card-month">{newsletter.monthLabel}</div>
                      <h2 className="archive-card-title">Coming soon</h2>
                    </div>
                    <div className="archive-card-action">New issue in progress</div>
                  </div>
                ) : (
                  <a className="archive-card" href={newsletter.url}>
                    <div>
                      <div className="archive-card-month">{newsletter.monthLabel}</div>
                      <h2 className="archive-card-title">{newsletter.monthLabel.replace(/\s+\d{4}$/, '')}</h2>
                    </div>
                    <div className="archive-card-action">Read newsletter &#8594;</div>
                  </a>
                )}
              </div>
            ))}
          </div>
        ) : <p className="archive-empty">The first newsletter will appear here after it is published.</p>}
      </main>
    </div>
  )
}

export default App
