/* Generated by Ward Newsletter Generator. */
import { useState } from 'react'
import './App.css'

const newsletters = [{"periodKey":"2026-09","monthLabel":"September 2026","title":"Willow Wood Ward - September 2026","url":"https://willowwoodward.github.io/WardNewsletters/n/sfVmImYb6j_f9zRGHWOy0Imo/"},{"periodKey":"2026-10","monthLabel":"October 2026","isComingSoon":true}]

function App() {
  const [showAllMonths, setShowAllMonths] = useState(false)
  const sortedNewsletters = [...newsletters].sort((first, second) => second.periodKey.localeCompare(first.periodKey))
  const cardNewsletters = [...sortedNewsletters].sort((first, second) => Number(Boolean(first.isComingSoon)) - Number(Boolean(second.isComingSoon)))

  return (
    <div className="archive-shell">
      <header className="archive-header">
        <div className="archive-brand">Willow Wood Ward</div>
        <button
          className="archive-qr-link"
          type="button"
          aria-expanded={showAllMonths}
          aria-controls="all-months"
          onClick={() => setShowAllMonths((isShowing) => !isShowing)}
        >
          {showAllMonths ? 'Hide all months' : 'See all months'}
        </button>
      </header>
      <main className="archive-main">
        <h1 className="archive-title">Ward Newsletter Archive</h1>
        <p className="archive-intro">Every monthly newsletter, gathered in one reliable place.</p>
        {showAllMonths && (
          <section className="all-months" id="all-months" aria-label="All newsletter months">
            {sortedNewsletters.map((newsletter) => newsletter.isComingSoon ? (
              <div className="all-months-item" key={newsletter.periodKey}>
                <span>{newsletter.monthLabel}</span>
                <span className="all-months-status">Coming soon</span>
              </div>
            ) : (
              <a className="all-months-item" href={newsletter.url} key={newsletter.periodKey}>
                <span>{newsletter.monthLabel}</span>
                <span className="all-months-status">Read newsletter &#8594;</span>
              </a>
            ))}
          </section>
        )}
        {sortedNewsletters.length > 0 ? (
          !showAllMonths && (
            <section className="archive-list" aria-label="Monthly newsletters">
              {cardNewsletters.map((newsletter) => newsletter.isComingSoon ? (
                <div className="archive-card" key={newsletter.periodKey}>
                  <div>
                    <div className="archive-card-month">{newsletter.monthLabel}</div>
                    <h2 className="archive-card-title">Coming soon</h2>
                  </div>
                  <div className="archive-card-action">New issue in progress</div>
                </div>
              ) : (
                <a className="archive-card" href={newsletter.url} key={newsletter.periodKey}>
                  <div>
                    <div className="archive-card-month">{newsletter.monthLabel}</div>
                    <h2 className="archive-card-title">{newsletter.monthLabel.replace(/\s+\d{4}$/, '')}</h2>
                  </div>
                  <div className="archive-card-action">Read newsletter &#8594;</div>
                </a>
              ))}
            </section>
          )
        ) : <p className="archive-empty">The first newsletter will appear here after it is published.</p>}
      </main>
    </div>
  )
}

export default App
